databases:
  - name: blog_projectdb
    plan: free
    databaseName: blog_project
    user: admin

services:
  - type: web
    plan: free
    name: blog_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn blog_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_projectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4